// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "adder": Application Media Types
//
// Command:
// $ goagen
// --design=github.com/shogo82148/goa-adder/design
// --out=$(GOPATH)/src/github.com/shogo82148/goa-adder
// --version=v1.3.1

package client
