consumes:
- application/json
- application/xml
- application/gob
- application/x-gob
host: localhost:8080
info:
  description: goaで遊んでみるテスト
  title: The adder API
  version: ""
paths:
  /:
    delete:
      operationId: operands#delete
      produces:
      - text/plain
      responses:
        "200":
          description: OK
      schemes:
      - http
      summary: delete operands
      tags:
      - operands
    patch:
      operationId: operands#patch
      produces:
      - text/plain
      responses:
        "200":
          description: OK
      schemes:
      - http
      summary: patch operands
      tags:
      - operands
    put:
      operationId: operands#put
      produces:
      - text/plain
      responses:
        "200":
          description: OK
      schemes:
      - http
      summary: put operands
      tags:
      - operands
  /add/{left}/{right}:
    get:
      description: leftとrightを足した値をレスポンスボディーに入れて返します
      operationId: operands#add
      parameters:
      - description: 左値
        in: path
        name: left
        required: true
        type: integer
      - description: 右値
        in: path
        name: right
        required: true
        type: integer
      produces:
      - text/plain
      responses:
        "200":
          description: OK
      schemes:
      - http
      summary: add operands
      tags:
      - operands
produces:
- application/json
- application/xml
- application/gob
- application/x-gob
responses:
  OK:
    description: OK
schemes:
- http
swagger: "2.0"
